spring:
  application:
    name: auth-service
  jackson:
    serialization:
      indent_output: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
