version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: autoevents-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: autoevents
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
