server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: event-service
          uri: http://localhost:8082
          predicates:
            - Path=/events/**
        - id: ticket-service
          uri: http://localhost:8083
          predicates:
            - Path=/tickets/**
        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/users/**
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /auth-service/v3/api-docs